protected/models/Absensi.php
<?php

/**
 * This is the model class for table "absensi".
 *
 * The followings are the available columns in table 'absensi':
 * @property integer $id
 * @property string $id_karyawan
 * @property string $tanggal
 * @property string $hari
 *
 * The followings are the available model relations:
 * @property Karyawan $idKaryawan
 * @property Pergantian[] $pergantians
 */
class Absensi extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'absensi';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('id_karyawan, tanggal, hari', 'required'),
			array('id_karyawan', 'length', 'max'=>20),
			array('hari', 'length', 'max'=>10),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, id_karyawan, tanggal, hari', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'idKaryawan' => array(self::BELONGS_TO, 'Karyawan', 'id_karyawan'),
			'pergantians' => array(self::HAS_MANY, 'Pergantian', 'id_absensi'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'id_karyawan' => 'Dosen',
			'tanggal' => 'Tanggal',
			'hari' => 'Hari',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('id_karyawan',$this->id_karyawan,true);
		$criteria->compare('tanggal',$this->tanggal,true);
		$criteria->compare('hari',$this->hari,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Absensi the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
        
         public static function hari()
	{
		return array(
			'Senin'=>'Senin',
			'Selasa'=>'Selasa',
			'Rabu'=>'Rabu',
			'Kamis'=>'Kamis',
			"Jum'at"=>"Jum'at",
			'Sabtu'=>'Sabtu',
		);
	}
        
}

protected/controllers/AbsensiController.php
<?php

class AbsensiController extends Controller
{
       
      
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
                        array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('updatepergantian','deletepergantian','createpergantian','riwayatabsen','viewriwayat','create','viewpergantian'),
				'users'=>array('@'),
			),
			array('allow',
				'actions'=>array('admin','index','delete','update','view'),
				'expression'=>'$user->getLevel()<=1',
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
                $absensi = $this->loadModel($id);
		$criteria = new CDbCriteria();
		$criteria->addCondition('id_absensi = ' . $id);
		$data = new CActiveDataProvider('Pergantian', array(
			'criteria' => $criteria
		));

		$this->render('view', array(
			'model' => $absensi,
			'data' => $data,
                      
		));
                
                 
	}
        
        public function actionViewriwayat($id)
	{
                $absensi = $this->loadModel($id);
		$criteria = new CDbCriteria();
		$criteria->addCondition('id_absensi = ' . $id);
		$data = new CActiveDataProvider('Pergantian', array(
			'criteria' => $criteria
		));

		$this->render('viewriwayat', array(
			'model' => $absensi,
			'data' => $data,
                      
		));
                
                 
	}
        
         public function actionViewpergantian($id)
	{
                $absensi = $this->loadModel($id);
		$criteria = new CDbCriteria();
                $nip=Yii::app()->user->getnip();
		$criteria->condition = "id_karyawan = :id_karyawan AND hari = :hari";
                $criteria->params = array (	
                ':id_karyawan' => $nip,
                ':hari' => $absensi->hari,
                );
		$data = new CActiveDataProvider('Jadwal', array(
			'criteria' => $criteria
		));

		$this->render('viewpergantian', array(
			'model' => $absensi,
			'data' => $data,
                      
		));
                
                 
	}
        
        public function actionCreatepergantian($id)
	{
		$model=new Pergantian();

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
                $criteria=new CDbCriteria;      //kita menggunakan criteria untuk mengetahui nomor terakhir dari database
                $criteria->select = 'id';   //yang ingin kita lihat adalah field "nilai1"
                $criteria->limit=1;             // kita hanya mengambil 1 buah nilai terakhir
                $criteria->order='id DESC';  //yang dimbil nilai terakhir
                $last = Absensi::model()->find($criteria);
		if(isset($_POST['Pergantian']))
		{
			$model->attributes=$_POST['Pergantian'];
                        $model->id_absensi=$last->id;
                        $model->kode_jadwal=$id;
			if($model->save())
				$this->redirect(array('viewpergantian','id'=>$model->id_absensi));
		}

		$this->render('createpergantian',array(
			'model'=>$model,
		));
	}
        
         public function actionUpdatepergantian($id)
	{
		$model = $this->loadpergantian($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
                
		if(isset($_POST['Pergantian']))
		{
			$model->attributes=$_POST['Pergantian'];
			if($model->save())
				$this->redirect(array('viewriwayat','id'=>$model->id_absensi));
		}

		$this->render('updatepergantian',array(
			'model'=>$model,
		));
	}
        
       

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Absensi;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Absensi']))
		{
			$model->attributes=$_POST['Absensi'];
                        $model->id_karyawan=Yii::app()->user->getnip();
			if($model->save())
				$this->redirect(array('viewpergantian','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
                
                
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Absensi']))
		{
			$model->attributes=$_POST['Absensi'];
			if($model->save())
				$this->redirect(array('index','id'=>$model->id));
		}

		$this->render('index',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();
                
		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
	}

	/**
	 * Lists all models.
	 */
        public function actionIndex()
	{
		
                
                $model=new Absensi('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Absensi']))
			$model->attributes=$_GET['Absensi'];

		$this->render('index',array(
			'model'=>$model,
		));
                
	}

	/**
	 * Manages all models.
	 */
	public function actionRiwayatabsen()
	{
          
                $criteria = new CDbCriteria();
                $id=Yii::app()->user->getnip();
		$criteria->addCondition('id_karyawan = ' . $id);
		$data = new CActiveDataProvider('Absensi', array(
			'criteria' => $criteria
		));

		$this->render('riwayatabsen',array(
			
                        'data' => $data,
		));    
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Absensi the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Absensi::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}
        
        private function loadpergantian($id)
	{
		$model = Pergantian::model()->findByPk($id);
		if($model===null) {
			throw new CHttpException(404, 'Buku tidak ditemukan');
		}
		return $model;
	}
        
        public function actionDeletepergantian($id)
	{
		$this->loadpergantian($id)->delete();
                
		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('view'));
	}

	/**
	 * Performs the AJAX validation.
	 * @param Absensi $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='absensi-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/absensi/_form.php
<?php
/* @var $this AbsensiController */
/* @var $model Absensi */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id'=>'absensi-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
        'type'=>'horizontal',
        'htmlOptions'=>array('class'=>'well'),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
            <div class="cotrol-group">
                <div class="control-label required" >
                    <?php echo $form->labelEx($model,'tanggal'); ?>
                </div>
                <div class="controls" > 
                    <?php $this->widget('zii.widgets.jui.CJuiDatePicker',
                    array(
                        'model'=>$model,
                        
                        'attribute'=>'tanggal',
                        'options' => array(
                            
                            'dateFormat'=>'yy-mm-dd',
                        ),
                    ));?>
                </div>
            </div>
	</div>
    </br>

	<div class="row">
		<?php echo $form->dropDownListRow($model,'hari',
			Jadwal::hari(),
			array('prompt'=>'===  Pilih Hari  ===',));
		?>
		
	</div>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
            'buttonType'=>'submit',
            'type'=>'primary',
            'label'=>'Simpan',
        )); ?>
        
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'type'=>'reset',
            'label'=>'Batal',
            'url'=>array('index'),
        )); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/absensi/_formpergantian.php
<?php
/* @var $this PergantianController */
/* @var $model Pergantian */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id'=>'pergantian-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
        'type'=>'horizontal',
        'htmlOptions'=>array('class'=>'well'),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<div class="row">
		<?php echo $form->dropDownListRow($model,'id_ruangan', CHtml::listData(
                    Ruangan::model()->findAll(), 'id', 'kode'),
			array(
				'empty' => '=== Pilih Ruangan =='
			)
		); ?>
		
	</div>

	<div class="row">
            <div class="cotrol-group">
                <div class="control-label required" >
                    <?php echo $form->labelEx($model,'tanggal'); ?>
                </div>
                <div class="controls" > 
                    <?php $this->widget('zii.widgets.jui.CJuiDatePicker',
                    array(
                        'model'=>$model,
                        
                        'attribute'=>'tanggal',
                        'options' => array(
                            
                            'dateFormat'=>'yy-mm-dd',
                        ),
                    ));?>
                </div>
            </div>
	</div>
    </br>

	<div class="row">
		<?php echo $form->dropDownListRow($model,'hari',
			Jadwal::hari(),
			array('prompt'=>'===  Pilih Hari  ===',));
		?>
		
	</div>

	<div class="row">
		<?php echo $form->textFieldRow($model,'jammulai',array('size'=>8,'maxlength'=>8)); ?>
		
	</div>

	<div class="row">
		<?php echo $form->textFieldRow($model,'jamselesai',array('size'=>8,'maxlength'=>8)); ?>
		
	</div>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
            'buttonType'=>'submit',
            'type'=>'primary',
            'label'=>'Simpan',
        )); ?>
        
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'type'=>'reset',
            'label'=>'Batal',
            'url'=>array('index'),
        )); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/absensi/_search.php
<?php
/* @var $this AbsensiController */
/* @var $model Absensi */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
        'type'=>'horizontal',
        'htmlOptions'=>array('class'=>'well'),
)); ?>

	<div class="row">
		<?php echo $form->dropDownListRow($model,'id_karyawan', CHtml::listData(
                    Karyawan::model()->findAll('jenis_id=2'), 'nip', 'nama'),
			array(
				'empty' => '=== Pilih Ruangan =='
			)
		); ?>
	</div>

	<div class="row">
            <div class="cotrol-group">
                <div class="control-label required" >
                    <?php echo $form->labelEx($model,'tanggal'); ?>
                </div>
                <div class="controls" > 
                    <?php $this->widget('zii.widgets.jui.CJuiDatePicker',
                    array(
                        'model'=>$model,
                        
                        'attribute'=>'tanggal',
                        'options' => array(
                            
                            'dateFormat'=>'yy-mm-dd',
                        ),
                    ));?>
                </div>
            </div>
	</div>
    </br>

	<div class="row">
		<?php echo $form->dropDownListRow($model,'hari',
			Jadwal::hari(),
			array('prompt'=>'===  Pilih Hari  ===',));
		?>
	</div>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
            'buttonType'=>'submit',
            'type'=>'primary',
            'label'=>'Cari',
        )); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/absensi/create.php
<?php
/* @var $this AbsensiController */
/* @var $model Absensi */
?>

<h1>Absensi Ketidakhadiran</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/absensi/createpergantian.php
<?php
/* @var $this PergantianController */
/* @var $model Pergantian */

?>

<h1>Pergantian Jadwal</h1>

<?php $this->renderPartial('_formpergantian', array('model'=>$model)); ?>

protected/views/absensi/index.php
<?php
/* @var $this AbsensiController */
/* @var $model Absensi */

$this->breadcrumbs=array(
	'Absensi'=>array('index'),
	'Kelola',
);

$this->menu=array(
	array('label'=>'List Absensi', 'url'=>array('index')),
	array('label'=>'Create Absensi', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#absensi-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Kelola Absensi</h1>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView', array(
	'type'=>'striped bordered condensed',
        'id'=>'absensi-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
        'template'=>"{items}",
	'columns'=>array(
		'id_karyawan',
		'tanggal',
		'hari',
                array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
              
			'template' => '{view} {delete}',
			'buttons' => array(
				'view' => array(
					'url' => 'Yii::app()->createUrl("/absensi/view", array("id" => $data->id))'
				),
                                'delete' => array(
					'url' => 'Yii::app()->createUrl("/absensi/delete", array("id" => $data->id))'
				)
			)
		),
		
	),
)); ?>

protected/views/absensi/riwayatabsen.php
<?php
/* @var $this AbsensiController */
/* @var $model Absensi */

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#absensi-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Riwayat Absensi</h1>

<?php $this->widget('bootstrap.widgets.TbGridView', array(
	'type'=>'striped bordered condensed',
        'id'=>'absensi-grid',
	'dataProvider'=>$data,
        'template'=>"{items}",
	'columns'=>array(
		'id_karyawan',
		'tanggal',
		'hari',
                array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
                        'htmlOptions' => array('width' => '3%'),
			'template' => '{view}',
			'buttons' => array(
				'view' => array(
					'url' => 'Yii::app()->createUrl("/absensi/viewriwayat", array("id" => $data->id))'
				),
			)
		),
		
	),
)); ?>

<table width="100%" border="0">
  <tr>
    <td align="right">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'type'=>'primary',
			'label'=>'Tambah',
			'url'=>array('create'),
		)); ?>
   </td>
  </tr>
</table>

protected/views/absensi/update.php
<?php
/* @var $this AbsensiController */
/* @var $model Absensi */

$this->breadcrumbs=array(
	'Absensis'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Absensi', 'url'=>array('index')),
	array('label'=>'Create Absensi', 'url'=>array('create')),
	array('label'=>'View Absensi', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Absensi', 'url'=>array('admin')),
);
?>

<h1>Update Absensi <?php echo $model->id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/absensi/view.php
<?php
/* @var $this AbsensiController */
/* @var $model Absensi */

$this->breadcrumbs=array(
	'Absensi'=>array('index'),
	$model->idKaryawan->nama,
);

$this->menu=array(
	array('label'=>'List Absensi', 'url'=>array('index')),
	array('label'=>'Create Absensi', 'url'=>array('create')),
	array('label'=>'Update Absensi', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Absensi', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Absensi', 'url'=>array('admin')),
);
?>

<h1>Lihat Data Absensi #<?php echo $model->idKaryawan->nama; ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		array(
                    'name'=> 'Nip',
                    'value'=>function($data){
                        return $data->id_karyawan;
                    }
		),
                array(
                    'name'=> 'Nama',
                    'value'=>function($data){
                        return $data->idKaryawan->nama;
                    }
		),
		'tanggal',
		'hari',
	),
)); ?>

<?php
$this->widget('bootstrap.widgets.TbGridView', array(
        'type'=>'striped bordered condensed',
	'id'=>'grid_pergantian',
	'dataProvider'=>$data,
        'template'=>"{items}",
	'columns'=>array(
                array(
                    'header' => 'No',
                    'value' => '$row+1',
                    'htmlOptions' => array('width' => '3%')
                    ),
                array(
                    'name'=> 'Tanggal',
                    'value'=>function($data){
                        return $data->tanggal;
                    }
		),
       
		 array(
                    'name'=> 'Mata Kuliah',
                    'value'=>function($data){
                        return $data->kodeJadwal->idMtk->nama;
                    }
		),
                 array(
                    'name'=> 'Ruangan',
                    'value'=>function($data){
                        return $data->kodeJadwal->idRuangan->kode;
                    }
		),
                array(
                    'name'=> 'Kelas',
                    'value'=>function($data){
                        return $data->kodeJadwal->kodeKelas->nama_kelas;
                    }
		),
                array(
                    'name'=> 'Hari',
                    'value'=>function($data){
                        return $data->hari;
                    }
		),
                 array(
                    'name'=> 'jam',
                    'value'=>function($data){
                        return $data->jammulai." s/d ".$data->jamselesai;
                    }
		),
                 array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
              
			'template' => '{delete}',
			'buttons' => array(
				
                                'delete' => array(
					'url' => 'Yii::app()->createUrl("/absensi/deletepergantian", array("id" => $data->id_pergantian))'
				)
			)
		),
                        
	),
));

protected/views/absensi/viewpergantian.php
<?php
/* @var $this AbsensiController */
/* @var $model Absensi */
?>

<h1>Lihat Data Absensi #<?php echo $model->idKaryawan->nama; ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		array(
                    'name'=> 'Nip',
                    'value'=>function($data){
                        return $data->id_karyawan;
                    }
		),
                array(
                    'name'=> 'Nama',
                    'value'=>function($data){
                        return $data->idKaryawan->nama;
                    }
		),
		'tanggal',
		'hari',
	),
)); ?>

<?php
$this->widget('bootstrap.widgets.TbGridView', array(
        'type'=>'striped bordered condensed',
	'id'=>'grid_pergantian',
	'dataProvider'=>$data,
        'template'=>"{items}",
	'columns'=>array(
                array(
                    'header' => 'No',
                    'value' => '$row+1',
                    'htmlOptions' => array('width' => '3%')
                    ),
       
		 array(
                    'name'=> 'Mata Kuliah',
                    'value'=>function($data){
                        return $data->idMtk->nama;
                    }
		),
                 array(
                    'name'=> 'Ruangan',
                    'value'=>function($data){
                        return $data->idRuangan->kode;
                    }
		),
                array(
                    'name'=> 'Kelas',
                    'value'=>function($data){
                        return $data->kodeKelas->nama_kelas;
                    }
		),
                array(
                    'name'=> 'Hari',
                    'value'=>function($data){
                        return $data->hari;
                    }
		),
                 array(
                    'name'=> 'jam',
                    'value'=>function($data){
                        return $data->jammulai." s/d ".$data->jamselesai;
                    }
		),
                        
                array(
			'class'=>'CButtonColumn',
			'template' => '{tambah}',
			'buttons' => array(
				'tambah' => array(
                                        'label'=>'Pergantian',
					'url' => 'Yii::app()->createUrl("/absensi/createpergantian", array("id" => $data->kode_jadwal))'
				),
			)
		),
	),
));

protected/views/absensi/viewriwayat.php
<?php
/* @var $this AbsensiController */
/* @var $model Absensi */
?>

<h1>Lihat Data Absensi #<?php echo $model->idKaryawan->nama; ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		array(
                    'name'=> 'Nip',
                    'value'=>function($data){
                        return $data->id_karyawan;
                    }
		),
                array(
                    'name'=> 'Nama',
                    'value'=>function($data){
                        return $data->idKaryawan->nama;
                    }
		),
		'tanggal',
		'hari',
	),
)); ?>

<?php
$this->widget('bootstrap.widgets.TbGridView', array(
        'type'=>'striped bordered condensed',
	'id'=>'grid_pergantian',
	'dataProvider'=>$data,
        'template'=>"{items}",
	'columns'=>array(
                array(
                    'header' => 'No',
                    'value' => '$row+1',
                    'htmlOptions' => array('width' => '3%')
                    ),
                array(
                    'name'=> 'Tanggal',
                    'value'=>function($data){
                        return $data->tanggal;
                    }
		),
       
		 array(
                    'name'=> 'Mata Kuliah',
                    'value'=>function($data){
                        return $data->kodeJadwal->idMtk->nama;
                    }
		),
                 array(
                    'name'=> 'Ruangan',
                    'value'=>function($data){
                        return $data->kodeJadwal->idRuangan->kode;
                    }
		),
                array(
                    'name'=> 'Kelas',
                    'value'=>function($data){
                        return $data->kodeJadwal->kodeKelas->nama_kelas;
                    }
		),
                array(
                    'name'=> 'Hari',
                    'value'=>function($data){
                        return $data->hari;
                    }
		),
                 array(
                    'name'=> 'jam',
                    'value'=>function($data){
                        return $data->jammulai." s/d ".$data->jamselesai;
                    }
		),
                 array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
               
			'template' => '{update} {delete}',
			'buttons' => array(
                                'update' => array(
					'url' => 'Yii::app()->createUrl("/absensi/updatepergantian", array("id" => $data->id_pergantian))'
				),
                                'delete' => array(
					'url' => 'Yii::app()->createUrl("/absensi/deletepergantian", array("id" => $data->id_pergantian))'
				)
			)
		),
	),
));?>
                
<table width="100%" border="0">
  <tr>
    <td align="right">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'type'=>'primary',
			'label'=>'Tambah',
			'url'=>array('viewpergantian','id'=>$model->id),
		)); ?>
   </td>
  </tr>
</table>